# Generated by Django 4.2.3 on 2023-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(default='76fb94fd-0bbb-4c6c-985b-8dbe930aa6b4', max_length=256, verbose_name='Пользовательский ID'),
        ),
    ]
