# Generated by Django 4.2.3 on 2023-09-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_film_picture_alter_film_file_alter_film_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film',
            field=models.CharField(max_length=256, verbose_name='Уникальный UUID4'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(default='e3b9c7c1-d796-4f29-a30e-e01f6f1c13ba', max_length=256, verbose_name='Пользовательский ID'),
        ),
    ]
