# Generated by Django 4.2.3 on 2023-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_film_film_alter_users_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(max_length=256, verbose_name='Пользовательский ID'),
        ),
    ]
