# Generated by Django 4.2.3 on 2023-09-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='userid',
        ),
    ]
